### ISSUE TITLE
Can't get XML parsing to work (repost)

### ISSUE THREAD

**Issue by Zageron** [microsoft/variable-substitution#11]
Apologies I couldn't reopen and I wasn't sure if you got my notifications from the closed issue.
#9 
```xml
<?xml version="1.0" encoding="utf-8"?>
<application xmlns="http://ns.adobe.com/air/application/32.0">
  <id>R3</id>
  <versionNumber>9.9.9</versionNumber>
</application>
```

```yaml
      - name: Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: 'application.xml'
        env:
          application.versionNumber: ${{ steps.versionNumber.outputs.tag }}
```

```bash

Variable Substitution
    application.versionNumber: 
Run microsoft/variable-substitution@v1
  with:
    files: application.xml
  env:
    application.versionNumber: 1.2.2
Applying variable substitution on XML file: application.xml
Skipped updating file: application.xml
##[error]Error: Failed to apply variable substitution
```
