### ISSUE TITLE
XML | Web.config | ##[error]Error: Failed to apply variable substitution

### ISSUE THREAD

**Issue by gojanpaolo** [microsoft/variable-substitution#14]
Hello. I can't seem to get Web.config XML variable substitution to work.

My .yml file has the following:

```yml
- uses: microsoft/variable-substitution@v1 
  with:
    files: '${{ github.workspace }}/WebApplication1/WebApplication3/Web.config'
  env:
    configuration.appSettings.foo: "b"
```

I also tried `appSettings.foo: "b"`

And I have the following in Web.config XML file:

```xml
<?xml...>
<configuration>
...
  <appSettings>
    <add key="foo" value="a"></add>
  </appSettings>
...
</configuration>
```

See the sample repo here: https://github.com/gojanpaolo/wm-pipeline-sb

Thank you.
