### ISSUE TITLE
How can we substitute attribute values of other XML Element like <machineKey>

### ISSUE THREAD

**Issue by gojanpaolo** [microsoft/variable-substitution#15]
Hello, I have the following Web.config XML file
```xml
<?xml...>
<configuration>
...
  <system.web>
    <machineKey validationKey="foo" decryptionKey="bar" />
  </system.web>
...
</configuration>
```

How do we change the `validationKey` and `descriptionKey` values?

I tried `system.web.machineKey.validationKey: "baz"` but it doesn't work. Also tried up to `validationKey: "baz"`

See sample repo here: https://github.com/gojanpaolo/wm-pipeline-sb

Thank you

**Comment by AmrutaKawade** [comment]
For XML substitution, currently we support only nodes "applicationSettings", "appSettings", "connectionStrings", "configSections" 

When your attribute is `key` or `name` then value of `value` attribute will be replaced.
If your XML is like below

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings>
    <add key="Foo" value="Bar" />
  </appSettings>
</configuration>
```
then your workflow should be like this

```
- uses: microsoft/variable-substitution@v1 
      with:
        files: 'Web.config'
      env:
        Foo: "foo"
```

which will change xml like below:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings>
    <add key="Foo" value="foo"/>
  </appSettings>
</configuration>
```

if your xml is like below:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings>
    <machineKey validationKey="foo" decryptionKey="bar" />
  </appSettings>
</configuration>
```

your workflow should be like this:

```
- uses: microsoft/variable-substitution@v1 
      with:
        files: 'Web.config'
      env:
        validationKey: "bar"
```

and replaced xml will be 

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings>
    <machineKey validationKey="bar" decryptionKey="bar"/>
  </appSettings>
</configuration>
```
