### ISSUE TITLE
Skipped updating file: .github/workflows/run_notebooks_mac.yml. But the variable does exists in yaml file

### ISSUE THREAD

**Issue by Wuliyuanulb** [microsoft/variable-substitution#19]
Hi,
Here is the yml which using Variable Substitution action:
![image](https://user-images.githubusercontent.com/37895561/102069081-41ebdf80-3e38-11eb-85c6-06d121b77bda.png)

And here is the yaml file that I wanna substitute:
![image](https://user-images.githubusercontent.com/37895561/102069362-9ee79580-3e38-11eb-99a5-4a6a613a9654.png)

However, the action failed with error:
![image](https://user-images.githubusercontent.com/37895561/102069435-baeb3700-3e38-11eb-998b-26405bd161e2.png)

Thanks

**Comment by arjgupta** [comment]
@Wuliyuanulb lets say you have a yaml file like so:

```
foobar:
  env:
    FOO: $VALUE
```

Then to substitute the value 'FOO' you need to define your workflow like so:


```
on: [push]
name: variable substitution in json, xml, and yml files

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: microsoft/variable-substitution@v1 
        with:
          files: "foobar.yaml"
        env:
          foobar.env.FOO: "value1"
```

In order to substitute the value for a key, you need to provide the json path of the key. in the action, we convert the yaml into json and use the jsonpath of the key to perform the substitution.
