### ISSUE TITLE
YAML file mistakenly taken as XML format

### ISSUE THREAD

**Issue by toshichi** [microsoft/variable-substitution#26]
I created an YAML file with some html context as value, and the file is mastakenly taken as XML file by the workflow.

It looks that some thing wrong in [`xmlDomUtility.js`](https://github.com/microsoft/variable-substitution/blob/ede5b92701e66ea752d76c4fc7e8888849edfdcd/lib/operations/xmlDomUtility.js)

`test.yml`
``` yaml
foo:
  bar:
    test: "<div>some html context in yaml file</div>"
```

`.github/workflows/test.yml`
``` yaml
name: 'Test Workflow'

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: replace secrets in yaml config
        uses: microsoft/variable-substitution@v1
        with:
          files: 'test.yml'
        env:
          foo.bar.test: ${{ secrets.ATESTSTRING }}
```

Output:
![image](https://user-images.githubusercontent.com/5460009/115231764-e8caea00-a150-11eb-9ba8-1f561e121d71.png)

It would be greatly appreciated if it can be fixed. Thanks!
