### ISSUE TITLE
Access Objects inside of an Array

### ISSUE THREAD

**Issue by zdmc23** [microsoft/variable-substitution#4]
(Thanks for the Action!)

It looks like the Access of Objects inside of an Array is not currently supported:

```
- uses: microsoft/variable-substitution@v1 
  with:
    files: './google-services.json'
  env:
    client[0].api_key[0].current_key: ${{ secrets.FIREBASE_API_KEY }}
```

Any near-term plans to support?
