### ISSUE TITLE
Value altered when substitude value in yaml

### ISSUE THREAD

**Issue by XunjieLiu** [microsoft/variable-substitution#40]
## How to reproduce

Here is part of my workflow script

```yaml
      - name: Variable substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: ./build/config.yaml
        env:
          sms.senderNumber: ${{ secrets.SMS_SENDER_NUMBER }}
```

And `secrets.SMS_SENDER_NUMBER` is `1069368924410002259`

But when the workflow is done, I check the actual config file, I got this

![image](https://user-images.githubusercontent.com/30891669/169698493-fc0f7cca-5adf-4ae4-adbe-0f930cb4fcbf.png)

The value is not the same as `secrets.SMS_SENDER_NUMBER`

### Check if GitHub secret correct

I use the following workflow debug GitHub action via ssh:

```yaml
name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        SMS_SENDER_NUMBER: ${{ secrets.SMS_SENDER_NUMBER }}
      run: |
        echo $SMS_SENDER_NUMBER >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
```

The secret value is correct

### Direct write value to the workflow YAML file

```yaml
      - name: Variable substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: ./build/config.yaml
        env:
          sms.senderNumber: 1069368924410002259
```

The result is, that the value is still altered, 

### Use double quotes

```yaml
      - name: Variable substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: ./build/config.yaml
        env:
          sms.senderNumber: "1069368924410002259"
```

The result is, that the value is still altered, 

### Use `sed` command

```yaml
      - name: Replace sender number
        run: sed -i 's/SMS_SENDER_NUMBER/${{ secrets.SMS_SENDER_NUMBER }}/' ./build/config.yaml
```

The result shows that the replacement is done correctly.

**Comment by dougireton** [comment]
I also get this error.

```yaml
  steps:
    - uses: microsoft/variable-substitution@v1
      with:
        files: ${{ github.action_path }}/my-ecs-task-def.json
      env:
        containerDefinitions.0.dockerLabels.com.datadoghq.tags.version: "${{ inputs.version }}"
        containerDefinitions.1.dockerLabels.com.datadoghq.tags.version: "${{ inputs.version }}"
```

When `inputs.version` == 15335e2, then the `microsoft/variable-substitution` action will inject `1533500` into the json file.
