### ISSUE TITLE
Target and replace XML connectionStrings node

### ISSUE THREAD

**Issue by RaviRamDhali** [microsoft/variable-substitution#41]
I am attempting to change a cnfgConnection.config > "connectionString" value using the following action and settings.

How do I target the connectionStrings > add > connectionString value?

```
- uses: microsoft/variable-substitution@v1 
   with:
       files: './Website/cnfgConnection.config'
   env:
          connectionStrings.add: "Data Source=prod.server.com;Initial Catalog=test;User ID=prod_tester;Password=xxxxxx"
```

Example XML

```
<?xml version="1.0"?>
<connectionStrings>
  <add name="DefaultConnectionString" connectionString="Data Source=test.server.com;Initial Catalog=test;User ID=tester;Password=xxxxxx" providerName="System.Data.SqlClient"/>
</connectionStrings>
```

**Comment by RaviRamDhali** [comment]
I got it working with the following code:

```
- uses: microsoft/variable-substitution@v1 
   with:
       files: './Website/cnfgConnection.config'
   env:
          connectionString: "Data Source=prod.server.com;Initial Catalog=test;User ID=prod_tester;Password=xxxxxx"
```
