### ISSUE TITLE
Can't figure out how to get XML parsing to work.

### ISSUE THREAD

**Issue by Zageron** [microsoft/variable-substitution#9]
```
      - name: Fix Air SDK Target Bug
        uses: microsoft/variable-substitution@v1
        if: matrix.os == 'windows-latest' && steps.cache-air-sdk.outputs.cache-hit != 'true'
        with:
          files: ${{ github.workspace }}\airsdk\frameworks\flex-config.xml
        env:
          flex-config.compiler.external-library-path.path-element: 'libs/player/32.0/playerglobal.swc'
```

It finds the file, but fails to walk the hierarchy and fill the value. There are no examples I can find on github that show usage with xml.

**Comment by eaarora-ms** [comment]
@Zageron I will need more information to investigate it further, Can you please let us know what is the error you are getting or that is the expected and achieved output that you are getting the action. Some logs would be of great help.

**Comment by asranja** [comment]
Please reopen with above information in order to help us debug further.

**Comment by Zageron** [comment]
```xml
<?xml version="1.0" encoding="utf-8"?>
<application xmlns="http://ns.adobe.com/air/application/32.0">
  <id>R3</id>
  <versionNumber>1.2.0</versionNumber>
</application>
```

```yaml
      - name: Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: 'application.xml'
        env:
          application.versionNumber: ${{ steps.versionNumber.outputs.tag }}
```

```bash

Variable Substitution
    application.versionNumber: 
Run microsoft/variable-substitution@v1
  with:
    files: application.xml
  env:
    application.versionNumber: 1.2.2
Applying variable substitution on XML file: application.xml
Skipped updating file: application.xml
##[error]Error: Failed to apply variable substitution
```
